import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

# --- 1. PAGE SETUP ---
st.set_page_config(page_title="Safe Haven Analysis", layout="wide", page_icon="📊")

st.title("📊 Market Regime & Safe Haven Dashboard")
st.markdown("Analyze how **Bitcoin** and **Gold** perform against the S&P 500 during Normal vs. Crisis market regimes (2015-2024).")

# --- 2. DATA LOADING ---
@st.cache_data
def load_data():
    # Load the data generated by your previous steps
    df = pd.read_csv("features_all_methods.csv", index_col=0, parse_dates=True)
    prices = pd.read_csv("raw_prices.csv", index_col=0, parse_dates=True)
    
    # Align dates
    common_idx = df.index.intersection(prices.index)
    return df.loc[common_idx], prices.loc[common_idx]

df, prices = load_data()

# --- 3. SIDEBAR CONTROLS ---
st.sidebar.header("Dashboard Controls")
asset_choice = st.sidebar.selectbox("Select Asset", ["Gold", "Bitcoin"])
regime_filter = st.sidebar.radio("Filter Market Regime", ["All Time", "Crisis Only", "Normal Only"])

# Map UI choices to dataset columns
ret_col = "gold_daily_ret" if asset_choice == "Gold" else "btc_daily_ret"
price_col = "Gold" if asset_choice == "Gold" else "BTC"
asset_color = "#FFD700" if asset_choice == "Gold" else "#F7931A"

# Filter data based on regime selection
if regime_filter == "Crisis Only":
    view_df = df[df["regime"] == 1]
    view_px = prices[df["regime"] == 1]
elif regime_filter == "Normal Only":
    view_df = df[df["regime"] == 0]
    view_px = prices[df["regime"] == 0]
else:
    view_df = df
    view_px = prices

# --- 4. KPI METRICS CARDS ---
st.subheader(f"Key Performance Indicators: {asset_choice} ({regime_filter})")

if len(view_df) > 0:
    mean_ret = view_df[ret_col].mean() * 100
    corr = view_df[ret_col].corr(view_df["market_daily_ret"])
    
    # Calculate Downside Beta (only on days SPY is negative)
    down_days = view_df[view_df["market_daily_ret"] < 0]
    if len(down_days) > 2:
        cov = np.cov(down_days[ret_col], down_days["market_daily_ret"])[0, 1]
        var = np.var(down_days["market_daily_ret"])
        down_beta = cov / var if var != 0 else np.nan
    else:
        down_beta = np.nan

    col1, col2, col3 = st.columns(3)
    col1.metric(label="Mean Daily Return", value=f"{mean_ret:+.3f}%")
    col2.metric(label="Correlation with Market", value=f"{corr:+.3f}")
    col3.metric(label="Downside Beta", value=f"{down_beta:+.3f}" if not np.isnan(down_beta) else "N/A", 
                delta="Safe Haven!" if down_beta < 0 else "Not a Hedge", delta_color="inverse")
else:
    st.warning("No data available for this filter.")

st.divider()

# --- 5. INTERACTIVE CHART: PRICE VS VIX ---
st.subheader(f"📈 {asset_choice} Price & Market Fear (VIX)")

fig_line = go.Figure()

# Plot Asset Price
fig_line.add_trace(go.Scatter(x=view_px.index, y=view_px[price_col], 
                              name=f"{asset_choice} Price", line=dict(color=asset_color, width=2)))

# Plot VIX on secondary axis
fig_line.add_trace(go.Scatter(x=view_df.index, y=view_df["vix_level"], 
                              name="VIX (Fear Gauge)", yaxis="y2", 
                              line=dict(color="red", width=1, dash="dot"), opacity=0.6))

# Highlight Crisis Regimes (if looking at All Time)
if regime_filter == "All Time":
    crisis_starts = df.index[df['regime'].diff() == 1].tolist()
    crisis_ends = df.index[df['regime'].diff() == -1].tolist()
    
    # Handle edge cases where crisis starts at beginning or ends at the very end
    if df['regime'].iloc[0] == 1: crisis_starts.insert(0, df.index[0])
    if df['regime'].iloc[-1] == 1: crisis_ends.append(df.index[-1])

    for start, end in zip(crisis_starts, crisis_ends):
        fig_line.add_vrect(x0=start, x1=end, fillcolor="red", opacity=0.15, layer="below", line_width=0)

fig_line.update_layout(
    yaxis=dict(title=f"{asset_choice} Price (USD)"),
    yaxis2=dict(title="VIX Level", overlaying="y", side="right"),
    hovermode="x unified",
    height=400,
    margin=dict(l=0, r=0, t=30, b=0)
)
st.plotly_chart(fig_line, use_container_width=True)

# --- 6. INTERACTIVE CHART: CRISIS SCATTER PLOT ---
st.subheader("📉 The Safe Haven Zone: Asset vs Market Return")
st.markdown("A true safe haven lands in the **Top-Left Quadrant** (Market crashes, Asset rises).")

fig_scatter = px.scatter(
    view_df, 
    x="market_daily_ret", 
    y=ret_col, 
    color=view_df["regime"].astype(str),
    color_discrete_map={"0": "#90A4AE", "1": "#E53935"},
    labels={"market_daily_ret": "S&P 500 Daily Return", ret_col: f"{asset_choice} Daily Return", "color": "Regime (1=Crisis)"},
    opacity=0.7
)

# Draw quadrant lines
fig_scatter.add_hline(y=0, line_width=1, line_dash="dash", line_color="black")
fig_scatter.add_vline(x=0, line_width=1, line_dash="dash", line_color="black")

# Highlight Safe Haven Zone
fig_scatter.add_shape(type="rect", x0=-0.15, y0=0, x1=0, y1=0.15,
                      fillcolor="green", opacity=0.1, layer="below", line_width=0)
fig_scatter.add_annotation(x=-0.075, y=0.075, text="SAFE HAVEN<br>ZONE", showarrow=False, font=dict(color="green", size=14))

fig_scatter.update_layout(height=500, margin=dict(l=0, r=0, t=30, b=0))
st.plotly_chart(fig_scatter, use_container_width=True)
